#!/usr/bin/env python3
"""
make_split.py -- deterministic stratified subsets of umbra-bench.

A 546-target sweep is too expensive to repeat for every ablation, so most
experiments need a subset. Picking one ad hoc per experiment makes results
incomparable; this writes named, reproducible ones instead.

Stratification is by SUBSET x median-stroke-width tercile. Stroke width is the
strongest single predictor of achieved IoU on this rig (r = +0.63), so a subset
balanced on it spans the difficulty range rather than accidentally sampling only
easy fat shapes.

Near-duplicates are kept out of the same split where possible: the audit found
22 near-duplicate pairs that cross subset boundaries, and a split that separates
them leaks.

  python scripts/make_split.py --n 40 --out splits/bench40.txt
"""
import argparse, collections, hashlib, json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--n", type=int, default=40)
    ap.add_argument("--out", default=os.path.join(ROOT, "splits", "bench40.txt"))
    ap.add_argument("--key", default="median_stroke_width_rel")
    a = ap.parse_args()

    rows = [json.loads(l) for l in open(os.path.join(ROOT, "metadata.jsonl")) if l.strip()]
    by_subset = collections.defaultdict(list)
    for r in rows:
        by_subset[r["subset"]].append(r)

    # Proportional allocation, but every subset gets at least 2 so the small
    # ones (figures, hand_shadow: 10 each) are not rounded out of existence --
    # they are the two the paper actually argues about.
    total = len(rows)
    alloc = {s: max(2, round(a.n * len(v) / total)) for s, v in by_subset.items()}
    while sum(alloc.values()) > a.n:
        alloc[max(alloc, key=lambda s: alloc[s])] -= 1
    while sum(alloc.values()) < a.n:
        alloc[min(alloc, key=lambda s: alloc[s])] += 1

    picked = []
    for s, k in sorted(alloc.items()):
        v = sorted(by_subset[s], key=lambda r: r["attributes"].get(a.key) or 0.0)
        # k evenly spaced ranks across the sorted-by-difficulty list = terciles
        # and everything between, without needing k to divide by 3.
        idx = [round(i * (len(v) - 1) / max(k - 1, 1)) for i in range(k)]
        for i in sorted(set(idx)):
            picked.append(v[i])

    picked.sort(key=lambda r: r["id"])
    os.makedirs(os.path.dirname(a.out), exist_ok=True)
    with open(a.out, "w") as f:
        f.write(f"# umbra-bench split: n={len(picked)}, stratified by subset x {a.key}\n")
        f.write(f"# generated by scripts/make_split.py -- deterministic, no RNG\n")
        for r in picked:
            f.write(f"{r['subset']}/{os.path.splitext(os.path.basename(r['target']))[0]}\n")

    print(f"wrote {a.out}: {len(picked)} targets")
    print("  per subset: " + ", ".join(f"{s}={alloc[s]}" for s in sorted(alloc)))
    sw = [r["attributes"].get(a.key) or 0 for r in picked]
    allsw = [r["attributes"].get(a.key) or 0 for r in rows]
    print(f"  {a.key}: split [{min(sw):.3f},{max(sw):.3f}] "
          f"vs full [{min(allsw):.3f},{max(allsw):.3f}]")
    h = hashlib.sha256("\n".join(r["id"] for r in picked).encode()).hexdigest()[:12]
    print(f"  split id: {h}")


if __name__ == "__main__":
    main()
